[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Distributed Data Analytics Using Python"
authors = [{name = "Joseph John", email = "joseph.john@anu.edu.au"}]
dynamic = ["version", "description"]
